version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8082:80'
    volumes:
      - .:/var/www/html
      - ./provision/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    container_name: php8.0-codegniter
    build:
      context: ./provision
    volumes:
      - .:/var/www/html

  vue:
    image: node:18-alpine
    command: sh -c "npm install && npm run start"
    ports:
      - 8083:8080
    working_dir: /app
    volumes:
      - ./vue-app:/app
